# Generated by Django 4.2.5 on 2024-07-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_choised',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Выбрано'),
        ),
    ]
