# Generated by Django 4.2.5 on 2024-07-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_image_is_choised'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Имя')),
                ('surname', models.TextField(blank=True, null=True, verbose_name='Фамилия')),
                ('patronymic', models.TextField(blank=True, null=True, verbose_name='Отчество')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('agree_to_recieve', models.BooleanField(blank=True, default=True, null=True, verbose_name='Согласен получать сообщения')),
                ('chosen_images', models.ManyToManyField(blank=True, related_name='users', to='main.image', verbose_name='Выбранные значки')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
